### ISSUE TITLE
AttributeError: type object 'Colors' has no attribute 'StaticMIX'. Did you mean: 'StaticRGB'?

### ISSUE THREAD

**Issue by BloodyToolzz** [billythegoat356/Specter#10]
I get this error whenever I launch specter.py, it was working a few minutes before this occured

Traceback (most recent call last):
  File "C:\Users\zeesh\Downloads\Specter-main\Specter-main\specter.py", line 44, in <module>
    purple = Col.StaticMIX([Col.blue, Col.purple])
AttributeError: type object 'Colors' has no attribute 'StaticMIX'. Did you mean: 'StaticRGB'?

**Comment by billythegoat356** [comment]
pip install -U pystyle
type this in your terminal

**Comment by BloodyToolzz** [comment]
Fixed, Thanks!
