### ISSUE TITLE
Randomly Appearing Error

### ISSUE THREAD

**Issue by ImInTheICU** [billythegoat356/Specter#15]
```
ValueError: invalid literal for int() with base 10: ''
```
Randomly appears...

🤔 

Edit: This is when running the obfuscated script, Full-TRACEBACK
```
                                                    ,exec(__import__('marshal').loads(__9830__[1]+__6807__[1]+__5788__[1]+__3109__[1]+__1160__[1]+__4175__[1]+__8327__[1]+__4193__[1]+__3820__[1]+__8926__[1]+__1371__[1]+__2541__[1]+__1715__[1]+__2089__[1]+__4709__[1]+__9963__[1]+__7177__[1]+__9409__[1]+__9928__[1]+__1429__[1]),globals())
  File "Specter", line 4, in <module>
  File "Specter", line 4, in <lambda>
  File "Specter", line 4, in <genexpr>
  File "Specter", line 3, in <lambda>
  File "Specter", line 3, in <genexpr>
ValueError: invalid literal for int() with base 10: ''
```

**Comment by billythegoat356** [comment]
Hello
This error is maybe caused because of the use of two different versions of Python.
For example: obfuscating the file with 3.9 and running it with 3.10 can cause an error similar to this one.
If you want your program to work on all versions and still have pretty strong obfuscation, you can try Hyperion.

**Comment by ImInTheICU** [comment]
> Hello This error is maybe caused because of the use of two different versions of Python. For example: obfuscating the file with 3.9 and running it with 3.10 can cause an error similar to this one. If you want your program to work on all versions and still have pretty strong obfuscation, you can try Hyperion.

Thanks for explaining this!
I love Hyperion but its strength is its weakness...
What I mean by this is because of its strength is makes it hard on some code and causes random errors...
I hade a error free program that randomly would get undefined errors and import errors for no reason...

Is there a possible way you could add a OBFUSCATED_IN = (Get_Python_Version) than when it errors throw back a message like 
`You need to execute this file in {OBFUSCATED_IN}!`

**Comment by ImInTheICU** [comment]
**Update: after some testing, obfuscation in 3.10 and running in 3.10 != 3.x will cause errors **BUT**... for some reason this still sometimes happens...
