### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by PandoricGalaxy** [billythegoat356/Specter#9]
![image](https://user-images.githubusercontent.com/86944806/171817290-1531cda6-0de3-4f54-8e1e-92a9ec39d938.png)
tried re obfuscating code

**Comment by billythegoat356** [comment]
you dont have to obfuscate your code 2 times...

**Comment by PandoricGalaxy** [comment]
> you dont have to obfuscate your code 2 times...

I didn't obfuscate 2 times u said there are chances of code having error so to reobfuscate it that's what I did which didn't work. (Re obfuscate the source code not obfuscate code)

**Comment by billythegoat356** [comment]
you have this error because you tried to execute the file on a different python version

**Comment by PandoricGalaxy** [comment]
Oh ok ok thx also do u know how can I import all modules when converting it to exe with nuitka? I mean do I have to manually type --include-package for every import that was in the source code?

**Comment by billythegoat356** [comment]
yeah try that, bcuz since the code is obfuscated nuitka cant know the modules

**Comment by PandoricGalaxy** [comment]
> yeah try that, bcuz since the code is obfuscated nuitka cant know the modules

I found the fix I just have to include the imports in obfiscated code

**Comment by billythegoat356** [comment]
yeah you can do this too
